<?php

define("DB_HOST",'PUT THE DATABASE HOST HERE');
define("DB_USER",'PUT THE DATABASE USERNAME HERE');
define("DB_PASSWORD",'PUT THE DATABASE USER PASSWORD HERE');
define("DB_NAME",'PUT THE DATABASE NAME HERE');